"""initial migration

Revision ID: 29e5db54707b
Revises: 
Create Date: 2026-03-31 10:51:43.298892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29e5db54707b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendars')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('ical_uid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ical_uid', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))

    op.create_table('calendars',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('ical_url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('synced_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
