"""add ical_id link to events

Revision ID: 4180df8059ae
Revises: 48507eb47ed8
Create Date: 2026-03-31 11:44:18.100613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4180df8059ae'
down_revision = '48507eb47ed8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ical_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_events_ical_id_calendars', 'calendars', ['ical_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_events_ical_id_calendars', type_='foreignkey')
        batch_op.drop_column('ical_id')

    # ### end Alembic commands ###
