"""add increment to cal ids

Revision ID: 48507eb47ed8
Revises: 29e5db54707b
Create Date: 2026-03-31 11:27:50.417016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48507eb47ed8'
down_revision = '29e5db54707b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ical_uid', sa.String(length=200), nullable=True))

    # Recreate calendars table with AUTOINCREMENT on the primary key.
    # SQLite requires a full table rebuild to add AUTOINCREMENT.
    with op.batch_alter_table('calendars', schema=None) as batch_op:
        batch_op.alter_column('id',
            existing_type=sa.Integer(),
            type_=sa.Integer(),
            autoincrement=True,
            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendars', schema=None) as batch_op:
        batch_op.alter_column('id',
            existing_type=sa.Integer(),
            type_=sa.Integer(),
            autoincrement=False,
            existing_nullable=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('ical_uid')
        batch_op.drop_column('description')
    # ### end Alembic commands ###
