"""add event cal feature

Revision ID: 64c9a5393e07
Revises: 29e5db54707b
Create Date: 2026-04-03 23:47:53.356291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64c9a5393e07'
down_revision = '29e5db54707b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ical_url', sa.String(length=500), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ical_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ical_uid', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))

        batch_op.create_foreign_key('fk_events_ical_id_calendars', 'calendars', ['ical_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_events_ical_id_calendars', type_='foreignkey')
        batch_op.drop_column('ical_id')
        batch_op.drop_column('ical_uid')
        batch_op.drop_column('description')


    op.drop_table('calendars')
    # ### end Alembic commands ###
