"""Added PFP boolean

Revision ID: 8c2b1ca7c45e
Revises: 9c0aa54ca76e
Create Date: 2026-05-05 17:01:51.976843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c2b1ca7c45e'
down_revision = '9c0aa54ca76e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatarurl', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatarurl')

    # ### end Alembic commands ###
