"""add source column to calendars

Revision ID: a52f59f3a6c3
Revises: eec1dfcd8186
Create Date: 2026-09-21 14:01:26.034313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a52f59f3a6c3'
down_revision = 'eec1dfcd8186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=32), server_default='generic', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendars', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###
