"""add email confirmation column

Revision ID: eec1dfcd8186
Revises: 0786cbeadab4
Create Date: 2026-06-16 15:55:36.713969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eec1dfcd8186'
down_revision = '0786cbeadab4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_confirmed', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###

    # Grandfather existing users in as already confirmed.
    users = sa.table('users', sa.column('email_confirmed', sa.Boolean()))
    op.execute(users.update().values(email_confirmed=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_confirmed')

    # ### end Alembic commands ###
